apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - local-storageclass.yaml
  - mongo-configmap.yaml
  - mongo-headless-svc.yaml
  - mongo-secret.yaml
  - mongo-statefullset.yaml
  - shop-configmap.yaml
  - shop-deployment.yaml
  - shop-service.yaml
