apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mongo-configmap.yaml
  - mongo-secret.yaml
  - deployment-configmap.yaml
  - mongo-service.yaml
  - mongo-statefullset.yaml
  - deployment.yaml
  - service.yaml
