apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: shopping-app
immutable: false
data:
  username: harsh
  mongodb.conf: |
    storage:
      dbPath: /data/db
    replication:
        replSetName: "rs0"
