apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: shopping-app
spec:
  clusterIP: None
  selector:
    app: myshop
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
