apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: shopping-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    matchLabels:
      app: myshop
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        app: myshop
    spec:
      initContainers:
        - name: init-mongo-keyfile
          image: busybox
          command:
            - sh
            - -c
            - "cp /tmp/keyfile /etc/mongo-keyfile/keyfile && chmod 400 /etc/mongo-keyfile/keyfile && chown 999:999 /etc/mongo-keyfile/keyfile"
          volumeMounts:
            - name: raw-keyfile
              mountPath: /tmp
            - name: mongo-keyfile
              mountPath: /etc/mongo-keyfile
      containers:
        - name: mongo
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: username
                  name: mongodb-config
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongodb-secret
            - name: MONGO_INITDB_DATABASE
              value: "shop"
          command:
            - mongod
            - "--bind_ip_all"
            - "--config=/etc/mongo/mongodb.conf"
            - "--keyFile=/etc/mongo-keyfile/keyfile" 
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
            - name: mongodb-config
              mountPath: /etc/mongo
            - name: mongo-keyfile
              mountPath: /etc/mongo-keyfile
      volumes:
        - name: mongodb-config
          configMap:
            name: mongodb-config
            items:
              - key: mongodb.conf
                path: mongodb.conf
        - name: raw-keyfile
          secret:
            secretName: mongodb-keyfile-secret
        - name: mongo-keyfile
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path-default
        resources:
          requests:
            storage: 1Gi

